name: Build and Publish Library

on:
  workflow_dispatch:
  release:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.12.2
      - uses: pnpm/action-setup@v2
        with:
          version: 9.11.0
      - run: pnpm install
      - run: pnpm build:vue
      - name: save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./packages/ui-vue/dist

  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.12.2
          registry-url: "https://npm.pkg.github.com"
      - uses: pnpm/action-setup@v2
        with:
          version: 9.11.0
      - name: install dependencies
        run: pnpm install
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./packages/ui-vue/dist
      - name: publish @filipvasilovski/ui-vue to npm
        run: pnpm publish --no-git-checks --registry=https://npm.pkg.github.com
        working-directory: ./packages/ui-vue
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
